### ISSUE TITLE
html.erb files opening in html syntax not html (rails) syntax

### ISSUE THREAD

**Issue by jbernsie** [atom/language-ruby-on-rails#14]
unsure if im doing something wrong? but i keep having to switch my syntax highlighting to rails html manually when opening `.html.erb` files?

**Comment by ollpu** [comment]
This issue is still present. Quite annoying, I have to say.

**Comment by TangMonk** [comment]
+1

**Comment by michalvalasek** [comment]
+1

**Comment by amingilani** [comment]
+1

**Comment by Vterebenin** [comment]
1. Create two .sublime-settings files by opening an .html.erb file and choose Open all with current extension as… twice. Once with regular HTML and again with Rails -> HTML (Rails)
2. Navigate to that folder by choose Preferences -> Browse Packages… and open both of your newly created .sublime-settings files.
3. In HTML.sublime-settings remove all the lines referring to rails or erb including html.erb
4. In HTML (Rails).sublime-settings remove all lines referring to plain html
