### ISSUE TITLE
About snippets in erb, it does not work.

### ISSUE THREAD

**Issue by haitaoxu** [atom/language-ruby-on-rails#3]
In the .erb file, I input "if" and then click 'tab' button, but it's not change to "<% if xxx %>"

**Comment by TangMonk** [comment]
@amnwebmaster 

Hi, I cannot found `Open in Atom` In Atom 1.0.5

**Comment by amingilani** [comment]
@amnwebmaster 

Like @TangMonk said, I can't Open in Atom anymore. Any ideas?
