### ISSUE TITLE
Unexpected indentation when defining a method

### ISSUE THREAD

**Issue by lrdiv** [atom/language-ruby-on-rails#4]
When a method is `def`ined and `end`ed without any code in that block, the `end` shoots over one tab when the user tries to put code between those 2 lines.

Current behavior in atom:
![indent](https://f.cloud.github.com/assets/2406864/2299149/2d381924-a0c8-11e3-9f8a-67f2e771c552.gif)

Expected behavior (from SublimeText 3 Beta):
![indent2](https://f.cloud.github.com/assets/2406864/2299182/c6d40cdc-a0c8-11e3-9471-264641f01314.gif)

**Comment by izuzak** [comment]
Seems like this was fixed in the meantime -- I'm having trouble reproducing that behavior:

![ruby](https://cloud.githubusercontent.com/assets/38924/9837040/f261927e-5a31-11e5-9560-14ef5d6b23b5.gif)

Let us know if you can still reproduce this. :v:
