### ISSUE TITLE
Zero not highlighted correctly

### ISSUE THREAD

**Issue by aried3r** [atom/language-ruby-on-rails#47]
![screen shot 2016-09-19 at 16 54 55](https://cloud.githubusercontent.com/assets/1301152/18636697/0a271cd0-7e8a-11e6-9122-ce03d24a4a38.png)

All other numbers are highlighted correctly (depending on what you think is 'correct' for negative ones).

**Comment by 50Wliu** [comment]
I believe this will been fixed starting with Atom 1.11.0.  Thanks for reporting though!

**Comment by aried3r** [comment]
This problem persists in Atom 1.11.1.

**Comment by 50Wliu** [comment]
Sorry, that was a typo.  I meant 1.12.0, and this can be verified as it is listed in the 1.12-beta changelog.

**Comment by aried3r** [comment]
Oh, guess that's why I didn't find any mention of it. Thanks!

I guess you mean this one: https://github.com/atom/language-ruby/pull/163

**Comment by 50Wliu** [comment]
Yep!  This language package inherits from language-ruby.
