### ISSUE TITLE
Failed to load a language-ruby-on-rails package grammar

### ISSUE THREAD

**Issue by elyaraujo** [atom/language-ruby-on-rails#55]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-ruby-on-rails](https://github.com/atom/language-ruby-on-rails) package 0.25.2

### Stack Trace

Failed to load a language-ruby-on-rails package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-ruby-on-rails\grammars\html (rails).json' in C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-ruby-on-rails\grammars\html (rails).json

Error: ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-ruby-on-rails\grammars\html (rails).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-ruby-on-rails/grammars/html (rails).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
color-picker 2.0.14 
minimap 4.19.0 
pigments 0.19.5 
```

**Comment by rsese** [comment]
Closing in favor of https://github.com/atom/language-java/issues/94 where this issue is being tracked, you can subscribe there for updates if you'd like.

**Comment by MarwenTlili** [comment]
just pause/disable language-ruby package in atom preferences
